name: audio_recorder_app
description: A simple audio recorder app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.3.2
  path_provider: ^2.0.14
  permission_handler: ^10.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
