name: Build Android APK on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Create MAUI project
      run: |
        dotnet new maui -n MyMauiApp

    - name: Replace MainPage.xaml.cs
      run: |
        $file = "MyMauiApp\MainPage.xaml.cs"
        $code = @"
using Microsoft.Maui.Controls;

namespace MyMauiApp
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();

            Content = new Label
            {
                Text = "Hello, MAUI Android!",
                VerticalOptions = LayoutOptions.Center,
                HorizontalOptions = LayoutOptions.Center
            };
        }
    }
}
"@
        Set-Content -Path $file -Value $code

    - name: Restore dependencies
      run: dotnet restore MyMauiApp\MyMauiApp.sln

    - name: Build APK
      run: dotnet publish MyMauiApp\MyMauiApp.csproj -c Release -f net7.0-android -o .\output

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: .\output\*.apk
