name: Flask Task Client

on:
  workflow_dispatch:

jobs:
  flask-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          pip install requests
      - run: |
          cat > client.py << 'EOF'
          import requests
          import time

          server_url = "https://testl.pythonanywhere.com"

          tasks = ["Action задача 1", "Action задача 2"]
          task_ids = []

          for task in tasks:
              r = requests.post(f"{server_url}/add_task", json={"task": task})
              task_ids.append(r.json()["task_id"])
              print(f"Добавлена задача {task} с id {r.json()['task_id']}")

          try:
              while task_ids:
                  for task_id in task_ids[:]:
                      requests.post(f"{server_url}/heartbeat/{task_id}")
                      r = requests.get(f"{server_url}/get_result/{task_id}")
                      data = r.json()
                      if "result" in data:
                          print(f"Результат задачи {task_id}: {data['result']}")
                          task_ids.remove(task_id)
                  time.sleep(2)
          except KeyboardInterrupt:
              print("Клиент завершает работу")
          EOF

          python client.py
