name: Build Android APK from scratch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Create MAUI project
      run: |
        dotnet new maui -n MyMauiApp
        cd MyMauiApp
        # Минимальный код MainPage.xaml.cs
        echo "namespace MyMauiApp; using Microsoft.Maui.Controls; public partial class MainPage : ContentPage { public MainPage() { InitializeComponent(); Content = new Label { Text = \"Hello, MAUI Android!\", VerticalOptions = LayoutOptions.Center, HorizontalOptions = LayoutOptions.Center }; } }" > MyMauiApp/MainPage.xaml.cs
        cd ..

    - name: Restore dependencies
      run: dotnet restore MyMauiApp/MyMauiApp.sln

    - name: Build APK
      run: dotnet publish MyMauiApp/MyMauiApp.csproj -c Release -f net7.0-android -o ./output

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ./output/*.apk
