name: Python Code Executor

on:
  workflow_dispatch:

jobs:
  python-task-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Task Loop
        run: |
          cat > runner.py << 'EOF'
          import requests
          import time

          SERVER_URL = "https://testl.pythonanywhere.com"

          while True:
              # Получаем новую задачу
              r = requests.get(f"{SERVER_URL}/get_task")
              task = r.json()
              task_id = task.get("task_id")
              code = task.get("code")

              if task_id:
                  print(f"Найдена задача {task_id}, выполняем...")
                  try:
                      # Локально выполняем код Python
                      local_vars = {}
                      exec(code, {}, local_vars)
                      result = str(local_vars)
                  except Exception as e:
                      result = f"Ошибка: {e}"

                  # Отправляем результат обратно
                  requests.post(f"{SERVER_URL}/submit_result", json={"task_id": task_id, "result": result})
                  print(f"Результат задачи {task_id} отправлен")
              else:
                  time.sleep(2)  # Ждём новые задачи
          EOF

          python runner.py
